<?php

/**
 * @file
 * File for node_cache module's hooks.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_view().
 */
function node_cache_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->getEntityType()->id() == 'user') {
    $build['#cache']['max-age'] = 0;
  }
}

/**
 * Implements hook_preprocess_block().
 */
function node_cache_preprocess_block(&$variables) {
  if ($variables['base_plugin_id'] == 'local_tasks_block') {
    $variables['#cache']['max-age'] = 0;
  }
}
