<?php

use Drupal\Core\Url;

// adds county to service node read more links
function county_node_routing_node_links_alter(&$links, $entity, &$context) {
    if ('teaser' === $context['view_mode'] &&
        'service' === $entity->getType() &&
        array_key_exists('node-readmore', $links['node']['#links'])
    ) {
        $county = \Drupal::routeMatch()->getParameter('county');
        $url = 'internal:/county/'.$county.$links['node']['#links']['node-readmore']['url']->toString();
        $links['node']['#links']['node-readmore']['url'] = Url::fromUri($url);
    }
}

// adds county variable to node teaser view
function county_node_routing_preprocess_node(&$variables) {
    if ($variables['teaser'] && 'service' === $variables['node']->getType()) {
        $variables['county'] = \Drupal::routeMatch()->getParameter('county');
    }
}
