## YAML Template.
---
system.profile.*.third_party.profile_reg_path::
  type: config_entity
  label: 'Profile Reg Path Settings'
  mapping:
    profile_reg_status:
      type: boolean
      label: 'Allow users to create seperte registratoin page for profile.'
    profile_reg_path_type:
      type: string
      label: 'Registraiton Path Settings'
    profile_reg_path:
      type: string
      label: 'URL for profile registation'
    profile_id:
      type: string
      label: 'Machine Name of profile'

      